<?php

/*********************************************************************
* Extension configuration file for ext "metadata".
*
* Generated by ext 02-01-2014 08:05 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Metadata extraction',
  'description' => 'PHP-based metadata extraction.',
  'category' => 'service',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'author_company' => 'Ecodev',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.1.0',
  'constraints' => 
  array (
    'depends' => 
    array (
      'cms' => '',
      'media' => '1.0.0-1.1.99',
      'typo3' => '6.1.6-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Change log http://forge.typo3.org/versions/show/2510',
);

?>