<?php

/*********************************************************************
* Extension configuration file for ext "metadata".
*
* Generated by ext 02-01-2014 08:22 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Metadata extraction',
  'description' => 'PHP-based metadata extraction.',
  'category' => 'service',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'author_company' => 'Ecodev',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'version' => '2.0.0-dev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'cms' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Change log http://forge.typo3.org/versions/show/2510',
);

?>
