<?php

/*********************************************************************
* Extension configuration file for ext "metadata".
*
* Generated by ext 25-07-2013 14:23 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Metadata extraction',
  'description' => 'PHP-based metadata extraction.',
  'category' => 'service',
  'author' => 'Media team',
  'author_email' => 'typo3-dev@lists.typo3.org',
  'author_company' => 'TYPO3 Association',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.1.0-dev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'cms' => '',
      'media' => '1.0.0-1.1.99',
      'typo3' => '6.1.1-6.1.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Version change log http://forge.typo3.org/projects/extension-metadata/versions/2450',
);

?>